### ISSUE TITLE
Generated images are erroneously cropped

### ISSUE THREAD

**Issue by clinew** [latex2html/latex2html#74]
Commit 73a2c8c4c6d0b4adb0e0b731421d086266acf248 causes images to be aggressively cropped, removing valid parts of the image.

Example after the commit: https://www.frostsnow.net/files/bad.png

Example before the commit: https://www.frostsnow.net/files/good.png

Any workarounds available?  I've looked at the image-generation code but so far a solution that would also solve the eqnarray issue has eluded me.

**Comment by danielgildea** [comment]
This looks like it might the problem that was fixed by commit [883010f14eb9d221e50e1dd1478504d648359794].

Does this commit fix this issue for you?  Can you try checking that \textwidth is wider than the figure in the latex file?  Can you provide a small example input file?

**Comment by clinew** [comment]
That commit does not fix the issue for me.  I initially detected the issue on `v2021.2` (coming from `v2017`), but it still fails on the latest (a95d4d5c67ba763bd6ad983b4f030f1428a85e5c).  There is a slight but irrelevant difference between the two, however: https://www.frostsnow.net/files/bad2.png

By running `\the\textwidth` in the `makeimage` environment I was able to get a value of `345.00pt`.  Combining this with the error message:
```
Overfull \hbox (259.39914pt too wide) in paragraph at lines 248--248
[][] 

:makeimage10:lthtmlCropMarkHeight:=109.92618pt

:makeimage10:lthtmlCropMarkDepth:=98.92616pt:1ex:=4.30554pt
Preview: Tightpage -32890 -32890 32890 32890
Overfull \hbox (259.39914pt too wide) in paragraph at lines 248--248
[][] 

:makeimage10:lthtmlCropMarkHeight:=109.92618pt

:makeimage10:lthtmlCropMarkDepth:=98.92616pt:1ex:=4.30554pt
Preview: Tightpage -32890 -32890 32890 32890
```
I'd reckon' that the total width of the image is `604pt`.

Example input file is here: https://www.frostsnow.net/files/sample.tar .  Run `make` to generate output.

The follow patch appears to provide the old behavior:
```
diff --git a/latex2html.pin b/latex2html.pin
index b17a3ca..29c7153 100755
--- a/latex2html.pin
+++ b/latex2html.pin
@@ -7276,8 +7276,8 @@ sub make_latex {
 \newdimen\lthtmlCropMarkHeight
 \newdimen\lthtmlCropMarkDepth
 \long\def\lthtmlTightVBoxA#1{\def\lthtmllabel{#1}
-    \setbox\lthtmlPageBox\vbox\bgroup\catcode`\_=8 }%
-\long\def\lthtmlTightVBoxZ{\egroup
+    \setbox\lthtmlPageBox\vbox\bgroup\hbox\bgroup\catcode`\_=8 }%
+\long\def\lthtmlTightVBoxZ{\egroup\egroup
     \lthtmlCropMarkHeight=\ht\lthtmlPageBox \advance \lthtmlCropMarkHeight 6pt
     \lthtmlCropMarkDepth=\dp\lthtmlPageBox
     \lthtmltypeout{^^J:\lthtmllabel:lthtmlCropMarkHeight:=\the\lthtmlCropMarkHeight}%
@@ -7563,7 +7563,7 @@ IMG.BOTTOM  { vertical-align:baseline; }
 CAPTION { caption-side:bottom; }
 
 DL.COMPACT > dt { float:left; padding-right: 1em; }
-BODY { width:95%; max-width:50em; margin:auto; }
+/*BODY { width:95%; max-width:50em; margin:auto; }*/
 
 /* implement both fixed-size and relative sizes */
 .XTINY         { font-size : xx-small }
```
I'm looking for one of the following:
1) No content width boundary, image is centered and not cropped (old behavior)
2) Width boundary, image is oversized and uncropped but centered (a few tweaks got it aligned to the left margin, which is terrible)
3) Width boundary, image is scaled to the width boundary but not cropped (saw this in a few of the old commits when bisecting)

**Comment by clinew** [comment]
Confirmed as working, thank you!

Though it does result in behavior 2, I worked around this by setting `$EXTERNAL_STYLESHEET` with the problematic `BODY` statement removed.  One caveat you might want to know about is that the `$EXTERNAL_STYLESHEET` variable is checked in `style_sheet()` when already in the directory in which the page will be generated, so a relative path value fails; I worked around this with the `Cwd::abs_path()` function.  Anyways, thanks again!
